### ISSUE TITLE
你好，求帮助。 红外扫码无法获取到数据。 NLS MT66  android v 8.1.0  版本号：MT66-X_V3.00.006

### ISSUE THREAD

**Issue by lvxianhao12** [mdddj/xindalu_scan_flutter#1]
D/XindaluScanFlutterPlugin( 4281): 广播输出action : nlscan.action.SCANNER_RESULT , 条码1Extra : SCAN_BARCODE1 , 条码2Extra : SCAN_BARCODE2 , 码制类型Extra : SCAN_BARCODE_TYPE
D/XindaluScanFlutterPlugin( 4281): 注意:如果获取不到数据,请核对以上数据和手机端配置信息是否一致!
D/XindaluScanFlutterPlugin( 4281): success !! 新大陆扫描配置初始化成功

**Comment by mdddj** [comment]
看一下手机的配置

**Comment by lvxianhao12** [comment]
请问如何看手机的配置？ 谢谢   NLS MT66 android v 8.1.0 版本号：MT66-X_V3.00.006 #1

**Comment by mdddj** [comment]
![IMG_0941](https://user-images.githubusercontent.com/29020213/129288499-9a75fe8e-8852-46a5-a0c7-59833208aeca.JPG)

配置要和这里的对应才能收到

**Comment by mdddj** [comment]
有疑问加群 667186542
